### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by mraible** [mattlewis92/generator-angular-library#28]
I used this library to create the [stormpath-sdk-angular](https://github.com/stormpath/stormpath-sdk-angular) project. My demo works fine, but when I try to run `npm link` in the project, then use it in another app, I get the following error. Any ideas what might be causing this? 

```
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) 
symbol 'StormpathModule'. Consider exporting the symbol (position 54:14 in the original .ts file), 
resolving symbol StormpathModule in /Users/mraible/ng-demo/node_modules/angular-
stormpath/dist/esm/src/stormpath.module.d.ts, resolving symbol StormpathModule in 
/Users/mraible/ng-demo/node_modules/angular-stormpath/dist/esm/src/index.d.ts, resolving 
symbol AppModule in /Users/mraible/ng-demo/src/app/app.module.ts, resolving symbol AppModule
 in /Users/mraible/ng-demo/src/app/app.module.ts
```

Steps to reproduce:

1. `git clone https://github.com/stormpath/stormpath-sdk-angular.git`
2. `cd stormpath-sdk-angular && npm link`
3. Create a new project with Angular CLI (e.g. `ng new ng-demo`)
4. Install Stormpath module `npm install angular-stormpath --save` into the new project
5. Import `StormpathModule` into `app.module.ts` and reference in `imports`. 
```
import { StormpathModule } from 'angular-stormpath';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    StormpathModule
  ]
```
6. Run `ng serve` and you'll see the error.

**Comment by mattlewis92** [comment]
I think your problem is that typescript 2.1 isn't compatible with AoT yet, try [downgrading](https://github.com/stormpath/stormpath-sdk-angular/blob/master/package.json#L103) to `~2.0.10` and then recompile your lib with ngc and it should start working.

**Comment by mraible** [comment]
Thanks for the tip. I tried downloading and now I get a number of different errors.

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/index.d.ts, resolving symbol StormpathModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/dist/esm/src/stormpath.module.d.ts, resolving symbol StormpathModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/dist/esm/src/stormpath.module.d.ts

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
Module not found: Error: Can't resolve 'ng2-webstorage' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js 18:0-47
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
Module not found: Error: Can't resolve 'angular2-cookie/core' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js 19:0-53
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath/token-store.manager.js
Module not found: Error: Can't resolve 'ng2-webstorage' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src/stormpath'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath/token-store.manager.js 6:0-53
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ../dev/stormpath-sdk-angular/dist/esm/src/stormpath/token-store.manager.js
Module not found: Error: Can't resolve 'angular2-cookie/core' in '/Users/mraible/dev/stormpath-sdk-angular/dist/esm/src/stormpath'
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath/token-store.manager.js 7:0-53
 @ ../dev/stormpath-sdk-angular/dist/esm/src/stormpath.module.js
 @ ../dev/stormpath-sdk-angular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
```

I tried installing the missing modules.

```
npm install ng2-webstorage --save
npm install angular2-cookie --save
```

Now I get a single error:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/node_modules/@angular/core/index.d.ts, resolving symbol StormpathModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/dist/esm/src/stormpath.module.d.ts, resolving symbol StormpathModule in /Users/mraible/ng-demo/node_modules/angular-stormpath/dist/esm/src/stormpath.module.d.ts
```

**Comment by mattlewis92** [comment]
Of the top of my head I'd recommend moving this [factory function](https://github.com/stormpath/stormpath-sdk-angular/blob/master/src/stormpath/stormpath.http.ts#L18-L22) into the [module declaration](https://github.com/stormpath/stormpath-sdk-angular/blob/master/src/stormpath.module.ts).

**Comment by mattlewis92** [comment]
The `angular2-cookie` also doesn't look AoT compatible as it's not shipped with any metadata.json files.

**Comment by mraible** [comment]
I tried moving the factory, but that doesn't help. I also tried removing all `{provide: ...}` from my module and removing ng2-webstorage and angular2-cookie. No dice.

**Comment by mraible** [comment]
Maybe this is all caused by `npm link`? I tried the following:

```
rm -rf node_modules/angular-stormpath
npm unlink angular-stormpath
cp -r ~/dev/stormpath-sdk-angular node_modules/angular-stormpath
rm -rf node_modules/angular-stormpath/node_modules/
ng serve
```

After these changes, I don't see any compile errors. However, I do see the following error in my browser console:

```
Uncaught TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (http://localhost:4200/vendor.bundle.js:77990:61)
    at assignAll (http://localhost:4200/vendor.bundle.js:113250:29)
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:113321:16)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:77952:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6861:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:21117:31)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:20992:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:4200/vendor.bundle.js:20980:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:21222:40)
    at http://localhost:4200/vendor.bundle.js:21180:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:21147:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:20831:50)
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:4200/vendor.bundle.js:20687:52)
    at http://localhost:4200/vendor.bundle.js:20758:72
```

**Comment by mraible** [comment]
Wahoo! Got it to work. Here's the steps that others might need when trying to do `npm link` when using this library with Angular CLI.

1. Make sure you're using TypeScript `~2.0.10` in the library module
2. Run `npm link project-name` in the project you want to test the library in
3. rm -rf `node_modules/project-name/node_modules`
4. Manually install any dependencies from project-name into the project

**Comment by mattlewis92** [comment]
Ah yeah I vaguely remember having similar problems before with trying to test AOT modules with npm link. My hacky solution in the end was just to keep publishing new versions to npm as betas until I got it to work. However the @ngtools/webpack plugin is now in a usable state, which allows you to AOT compile your demo app so these things can easily be tested in dev mode. Once webpack 2 is stable I'll add support for it into the original generator. Glad you got everything resolved! 😀
