### ISSUE TITLE
packageManager is not defined

### ISSUE THREAD

**Issue by dolanmiu** [mattlewis92/generator-angular-library#69]
When I try to generate using this library, I get:

```
packageManager is not defined
    at eval (eval at compile (/usr/local/lib/node_modules/generator-angular-library/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:12)
    at returnedFn (/usr/local/lib/node_modules/generator-angular-library/node_modules/ejs/lib/ejs.js:580:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-angular-library/node_modules/ejs/lib/ejs.js:384:37)
    at process (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
    at files.forEach.file (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (native)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-angular-library/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
```

**Comment by mattlewis92** [comment]
Thanks for reporting, fix released as 3.0.6 😄
